site_name: 不好奇
site_url: https://buhaoqi.com/

# Repository
repo_name: buhaoqi/buhaoqi
repo_url: https://github.com/buhaoqi/buhaoqi.git

# Copyright
copyright: Copyright &copy; 2021 - 2023 不好奇 <br /><a target="_blank" href="https://beian.miit.gov.cn/" ><img src="/assets/gonganbei.png" />湘公网安备 43011102002242号</a> <a target="_blank" href="https://beian.miit.gov.cn/" >湘ICP备2022014446号-1</a>
 
# Configuration
theme:
  name: material
  # custom_dir: overrides
  language: zh
  palette:
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换至普通模式
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换至黑暗模式
      icon:
        admonition:
          <type>: <icon> 
  logo: assets/logo.svg
  features:
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  plugins:
    - mkdocs-video
    - glightbox # 图片放大
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list # 许使用特殊语法将 HTML 属性和 CSS 类添加到几乎每个 Markdown 内联和块级元素
  - md_in_html # 允许在HTML中编写Markdown
  - admonition
  - pymdownx.details
  
# Page tree
nav:
  - 首页: index.md
  - Scratch3.0教程:
    - scratch/index.md
    - scratch/about-scratch.md
    - scratch/user-interface.md
    - scratch/sprite.md
    - scratch/blocks.md
    - scratch/costume.md
    - scratch/stage.md
    - scratch/backdrop.md
    - scratch/broadcast.md
    - scratch/extensions.md
    - scratch/preparation.md
    - scratch/notes.md
  